=== ijkml/human/app/types/work-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "details": {
      "type": "string"
    },
    "link": {
      "type": "string"
    },
    "kind": {
      "type": "string",
      "enum": ["Personal", "Contract", "Full-time"]
    },
    "period": {
      "type": "string"
    },
    "roles": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tools": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "wip": {
      "type": "boolean",
      "optional": true
    },
    "git": {
      "type": "string",
      "optional": true
    },
    "credits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "link": {
            "type": "string"
          }
        },
        "required": ["name", "link"]
      },
      "optional": true
    }
  },
  "required": ["id", "name", "details", "link", "kind", "period", "roles", "tools"]
}

=== ijkml/human/content/work/2.human-v0.json
{
  "id": "human-v0",
  "wip": true,
  "name": "Human v0",
  "details": "The first public version of my website/portfolio. A minimalist dark-mode design inspired by bold grotesque grids, and towering skyscrapers.",
  "kind": "Full-time",
  "link": "https://ijkml.vercel.app",
  "period": "2015 - Present",
  "roles": ["Designer", "Developer"],
  "tools": ["Vue/TS", "Nuxt", "Uno/Sass", "Nuxt Studio"],
  "git": "https://github.com/ijkml/human",
  "credits": [{
    "name": "Design inspiration â€” Bequant",
    "link": "https://www.bequant.com/"
  }]
}

=== ijkml/human/content/work/1.moi-immigration.json
{
  "id": "moi-immigration",
  "name": "MOI Immigration",
  "details":
    "I collaborated with MOI Immigration Solutions, a Canadian Immigration Consulting firm with offices in Edmonton, Canada, and Ibadan, Nigeria. Together with their in-house team, we transitioned their website from WordPress to a modern, responsive, and user-friendly design.",
  "kind": "Contract",
  "period": "Nov 2022",
  "link": "https://moiis.netlify.app/",
  "roles": ["Developer"],
  "tools": ["Vue/TS", "Nuxt", "Windi/Less", "Umami"]
}

=== ijkml/human/content/work/4.pennypay.json
{
  "id": "pennypay",
  "name": "PennyPay",
  "details":
    "Designed and developed a pseudo-minimalist landing page for a fictional global payments and commerce company, incorporating a sleek dark mode for a modern and engaging user experience.",
  "kind": "Personal",
  "period": "Jan - Feb 2023",
  "link": "https://pennypay.netlify.app/",
  "roles": ["Designer", "Developer"],
  "tools": ["Vue/TS", "Nuxt", "Uno/Sass", "Headless UI", "Iconify"],
  "git": "https://github.com/ijkml/PennyPay"
}

=== ijkml/human/content/work/2.voe.json
{
  "id": "voe",
  "name": "Voe",
  "details": "Voe is a responsive demo of Egbo Prosper's Voe Airport landing page (pun unintened). The website features a sleek dark mode and GPT-translation in 5 languages: English, Spanish, French, Japanese, and Chinese).",
  "kind": "Personal",
  "period": "Nov 2022 - Jan 2023",
  "link": "https://voey.netlify.app/",
  "roles": ["Developer"],
  "tools": [
    "Vue/TS",
    "Nuxt",
    "Nuxt i18n",
    "Uno/Sass",
    "Headless UI",
    "Iconify"
  ],
  "git": "https://github.com/ijkml/Voe",
  "credits": [
    {
      "name": "Egbo Prosper (Design)",
      "link": "https://www.behance.net/gallery/156009795/Voe-_-Landing-page-UI-design"
    }
  ]
}
